-- This migration file has been deprecated.
-- The city_weather_data table is no longer used.
-- Weather data is now managed in the weather_forecasts table.
--
-- To remove the old table, run:
-- DROP TABLE IF EXISTS city_weather_data CASCADE;